name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: dotnet publish Shellf.Application/Shellf.Application.csproj --configuration Release --output ./publish /p:Version=${{ github.event.release.tag_name }}

    - name: Create a zip file of the binaries
      run: |
        mkdir -p release
        zip -r release/shellf.${{ github.event.release.tag_name }}.zip ./publish/*
    
    - name: Upload Binaries
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release/shellf.${{ github.event.release.tag_name }}.zip
        asset_name: shellf.${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
